"""Verilog/VAMS text emission helpers."""
from __future__ import annotations

import math
import re
from pathlib import Path

BANNER = """\
// -----------------------------------------------------------------------------
// {title}
// generated by pllsim.export — DO NOT EDIT (regenerate from the Python config)
// {origin}
// -----------------------------------------------------------------------------
"""


def vreal(x: float) -> str:
    """Format a float as a valid Verilog real literal, round-trip exact."""
    x = float(x)
    if math.isnan(x) or math.isinf(x):
        raise ValueError(f"cannot emit non-finite parameter value: {x}")
    s = f"{x:.17g}"
    # a real literal must contain '.' or an exponent
    if re.fullmatch(r"-?\d+", s):
        s += ".0"
    return s


def vint(x) -> str:
    xi = int(x)
    if xi != x:
        raise ValueError(f"expected integer parameter, got {x}")
    return str(xi)


def param_real(name: str, value: float, comment: str) -> str:
    return f"  parameter real {name} = {vreal(value)},  // {comment}"


def module_header(title: str, origin: str) -> str:
    return BANNER.format(title=title, origin=origin)


def write_file(path: Path, text: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text)
    return path


def check_balanced(text: str) -> bool:
    """Sanity: module/endmodule pairs balanced (used by structure tests)."""
    n_mod = len(re.findall(r"^\s*(?:module|macromodule)\b", text, re.M))
    n_end = len(re.findall(r"^\s*endmodule\b", text, re.M))
    return n_mod == n_end and n_mod > 0
